= Parameters

The parent key for all of the following parameters is `aws_load_balancer_controller`.

== `name`

[horizontal]
type:: string
default:: `aws-load-balancer-controller`

Release name used for the Helm deployment.

== `namespace`

[horizontal]
type:: string
default:: `kube-system`

The namespace in which to deploy this component.

== `charts.aws_load_balancer_controller.source`

[horizontal]
type:: string
default:: `https://aws.github.io/eks-charts`

Upstream Helm repository URL for `aws-load-balancer-controller`.

== `charts.aws_load_balancer_controller.version`

[horizontal]
type:: string
default:: `3.0.0`

Upstream Helm chart version to deploy.

== `images.controller.repository`

[horizontal]
type:: string
default:: `public.ecr.aws/eks/aws-load-balancer-controller`

Controller image repository used in chart values.

== `images.controller.tag`

[horizontal]
type:: string
default:: `v3.0.0`

Controller image tag used in chart values.

== `helm_values`

[horizontal]
type:: dict
default:: `{"clusterName": "${cluster:name}", "image": "${aws_load_balancer_controller:images:controller}", "enableCertManager": true}`

Values passed directly to the upstream Helm chart.
For all available chart values, see https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller[Artifact Hub].

== `helm_values.clusterName`

[horizontal]
type:: string
default:: `${cluster:name}`

Kubernetes cluster name passed to the Helm chart.

== `helm_values.image`

[horizontal]
type:: dict
default:: `${aws_load_balancer_controller:images:controller}`

Image configuration map passed to the Helm chart.

== `helm_values.enableCertManager`

[horizontal]
type:: boolean
default:: `true`

Enable cert-manager integration for webhook certificates.
This keeps rendered manifests deterministic across compiles.
cert-manager is a hard dependency for this component.
Deploy cert-manager with https://github.com/projectsyn/component-cert-manager[projectsyn/component-cert-manager].

== Example

[source,yaml]
----
aws_load_balancer_controller:
  namespace: kube-system
  charts:
    aws_load_balancer_controller:
      version: 3.0.0
  images:
    controller:
      tag: v3.0.0
----
